- hosts: localhost
  become: true
  vars:
    username: ericovis
    ansible_python_interpreter: /usr/local/bin/python
    zsh_plugins:
      - git
      - pipenv
      - ng
      - aws
    extra_paths:
      - "$HOME/bin"
      - "$PYENV_ROOT/bin"
      - "$PYENV_ROOT/shims"
    env_vars:
      PYENV_ROOT: $HOME/.pyenv
      LANG: en_US.UTF-8

  tasks:  
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        regexp: '^{{ username }}'
        line: '{{ username }} ALL = (ALL) NOPASSWD:ALL'    

    - name: Ensure NVM is installed
      become: false
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      args:
        creates: "~/.nvm/nvm.sh"

    - name: Ensure needed brew packages are present
      become: false
      homebrew:
        name: 
          - htop
          - ncdu
          - rbenv
          - ruby-build
          - pyenv
        state: present
        update_homebrew: true
  
    - name: Ensure gentoo theme is set
      become: false
      lineinfile:
        dest: ~/.zshrc
        state: present
        regexp: 'ZSH_THEME=.*'
        line: 'ZSH_THEME="gentoo"'
    
    - name: Ensure pyenv is initiated
      become: false
      lineinfile:
        dest: ~/.zshrc
        state: present
        line: 'eval "$(pyenv init -)"'

    - name: Ensure needed env vars are set
      become: false
      lineinfile:
        dest: ~/.zshrc
        state: present
        insertbefore: "export PATH=.*"
        line: 'export {{ item.key }}="{{ item.value }}"'
      with_dict: "{{ env_vars }}"
  
    - name: Ensure zsh plugins are set
      become: false
      lineinfile:
        dest: ~/.zshrc
        state: present
        regexp: 'plugins=.*'
        line: 'plugins=( {{ zsh_plugins | join(" ") }} )'

    - name: Ensure extra PATH variables are on .zshrc
      become: false
      lineinfile:
        dest: ~/.zshrc
        state: present
        regexp: 'export PATH=.*'
        line: 'export PATH={{ extra_paths | join(":") }}:$PATH'
